(WIP) try K2
mvn \
  -Dkotlin.version=1.8.21 \
  -Dkotlin.compiler.languageVersion=2.0 \
  -Dbytecode.version=8 \
  clean package

Updates
* KotlinWhenExpressionTarget
  - change of location of branches
  - Enum.entries
* KotlinCoroutineTarget - first line was empty, now fully covered
* KotlinDataClassTarget - synthetic `copy$default`

Failed tests:
  execute_assertions_in_comments(org.jacoco.core.test.validation.kotlin.KotlinWhenExpressionTest): Instructions (KotlinWhenExpressionTarget.kt:67) expected:<[FUL]LY_COVERED> but was:<[PART]LY_COVERED>
  execute_assertions_in_comments(org.jacoco.core.test.validation.kotlin.KotlinDelegatesTest): Instructions (KotlinDelegatesTarget.kt:20) expected:<[FUL]LY_COVERED> but was:<[PART]LY_COVERED>
  all_missed_instructions_should_have_line_number(org.jacoco.core.test.validation.kotlin.KotlinDelegatesTest): sum of missed instructions of all lines should be equal to missed instructions of file expected:<74> but was:<71>
  execute_assertions_in_comments(org.jacoco.core.test.validation.kotlin.KotlinLateinitTest): Instructions (KotlinLateinitTarget.kt:26) expected:<[FUL]LY_COVERED> but was:<[PART]LY_COVERED>