(WIP) try Kotlin 1.8.0-RC
JVM target 1.6 is no longer supported. Please migrate to JVM target 1.8 or above

Failed tests:
  execute_assertions_in_comments(org.jacoco.core.test.validation.kotlin.KotlinWhenExpressionTest): Instructions (KotlinWhenExpressionTarget.kt:67) expected:<[FUL]LY_COVERED> but was:<[PART]LY_COVERED>
  execute_assertions_in_comments(org.jacoco.core.test.validation.kotlin.KotlinLateinitTest): Instructions (KotlinLateinitTarget.kt:26) expected:<[FUL]LY_COVERED> but was:<[PART]LY_COVERED>